# Background
## Loading in our library and functions
```{r}
library(tidyverse)
source("../R/moving-average.R")
```
# Data 
## Read in CSV files
```{r}
Bisley1 <- read_csv(
  "../data/knb-lter-luq.20.4923064/QuebradaCuenca1-Bisley.csv"
)
Bisley2 <- read_csv(
  "../data/knb-lter-luq.20.4923064/QuebradaCuenca2-Bisley.csv"
)
Bisley3 <- read_csv(
  "../data/knb-lter-luq.20.4923064/QuebradaCuenca3-Bisley.csv"
)
PRM <- read_csv("../data/knb-lter-luq.20.4923064/RioMameyesPuenteRoto.csv")
```
## Data Exploration
```{r}
head(Bisley1)
head(Bisley2)
head(Bisley3)
head(PRM)
colnames(Bisley1)
colnames(Bisley2)
colnames(Bisley3)
colnames(PRM)
```
# Methods
## Create the lines 
```{r}
bq1_smoothed <- moving_average(Bisley1)
bq2_smoothed <- moving_average(Bisley2)
bq3_smoothed <- moving_average(Bisley3)
prm_smoothed <- moving_average(PRM)

## Combining into a long format tibble
potassium_long <- bind_rows(
  bq1_smoothed |> mutate(stream = "BQ1"),
  bq2_smoothed |> mutate(stream = "BQ2"),
  bq3_smoothed |> mutate(stream = "BQ3"),
  prm_smoothed |> mutate(stream = "PRM")
)
```
# Results
## Graph
```{r}
ggplot(potassium_long, aes(x = window_start, y = k_mgl, color = stream)) +
  geom_line() +
  labs(y = "K mg/L", x = "Year", color = "Stream")
```
